# Workflow name
name: "Chromatic"

on: [push]

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.13.0]

    env:
      NODE_ENV: test

    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - run: yarn

    - name: Publish to Chromatic
      uses: chromaui/action@v1
      with:
        projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        workingDir: packages/frontend
